default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: <%= ENV.fetch("DB_USERNAME") %>
  PASSWORD: <%= ENV.fetch("DB_PASSWORD") %>

development:
  <<: *default
  database: scraper_dev

test:
  <<: *default
  database: scraper_test

production:
  <<: *default
  database: scraper_production
